
CREATE DATABASE IF NOT EXISTS wifirental;
USE wifirental;
CREATE TABLE partners (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255));
CREATE TABLE hotspots (id INT AUTO_INCREMENT PRIMARY KEY, partner_id INT, name VARCHAR(255));
